import SidoNameList from "./SidoNameList.js";
import { request } from "./api.js";

const DATA = await request("getCtprvnRltmMesureDnsty", "서울");

// 더미 데이터
const DUMMY_DATA = {
  response: {
    body: {
      totalCount: 40,
      items: [
        {
          so2Grade: "1",
          coFlag: null,
          khaiValue: "55",
          so2Value: "0.002",
          coValue: "0.4",
          pm25Flag: null,
          pm10Flag: null,
          o3Grade: "2",
          pm10Value: "12",
          khaiGrade: "2",
          pm25Value: "1",
          sidoName: "서울",
          no2Flag: null,
          no2Grade: "1",
          o3Flag: null,
          pm25Grade: "1",
          so2Flag: null,
          dataTime: "2021-09-05 12:00",
          coGrade: "1",
          no2Value: "0.002",
          stationName: "도봉구",
          pm10Grade: "1",
          o3Value: "0.036",
        },
        {
          so2Grade: null,
          coFlag: null,
          khaiValue: "-",
          so2Value: "-",
          coValue: "0.3",
          pm25Flag: null,
          pm10Flag: null,
          o3Grade: "2",
          pm10Value: "5",
          khaiGrade: null,
          pm25Value: "1",
          sidoName: "서울",
          no2Flag: null,
          no2Grade: "1",
          o3Flag: null,
          pm25Grade: null,
          so2Flag: "자료이상",
          dataTime: "2021-09-05 12:00",
          coGrade: "1",
          no2Value: "0.003",
          stationName: "은평구",
          pm10Grade: "1",
          o3Value: "0.048",
        },
        {
          so2Grade: "1",
          coFlag: null,
          khaiValue: "58",
          so2Value: "0.002",
          coValue: "0.3",
          pm25Flag: null,
          pm10Flag: null,
          o3Grade: "2",
          pm10Value: "5",
          khaiGrade: "2",
          pm25Value: "4",
          sidoName: "서울",
          no2Flag: null,
          no2Grade: "1",
          o3Flag: null,
          pm25Grade: "1",
          so2Flag: null,
          dataTime: "2021-09-05 12:00",
          coGrade: "1",
          no2Value: "0.003",
          stationName: "서대문구",
          pm10Grade: "1",
          o3Value: "0.040",
        },
        {
          so2Grade: "1",
          coFlag: null,
          khaiValue: "60",
          so2Value: "0.002",
          coValue: "0.3",
          pm25Flag: null,
          pm10Flag: null,
          o3Grade: "2",
          pm10Value: "12",
          khaiGrade: "2",
          pm25Value: "2",
          sidoName: "서울",
          no2Flag: null,
          no2Grade: "1",
          o3Flag: null,
          pm25Grade: "1",
          so2Flag: null,
          dataTime: "2021-09-05 12:00",
          coGrade: "1",
          no2Value: "0.007",
          stationName: "마포구",
          pm10Grade: "1",
          o3Value: "0.042",
        },
        {
          so2Grade: "1",
          coFlag: null,
          khaiValue: "-",
          so2Value: "0.003",
          coValue: "0.3",
          pm25Flag: null,
          pm10Flag: null,
          o3Grade: "2",
          pm10Value: "12",
          khaiGrade: null,
          pm25Value: "4",
          sidoName: "서울",
          no2Flag: null,
          no2Grade: "1",
          o3Flag: null,
          pm25Grade: null,
          so2Flag: null,
          dataTime: "2021-09-05 12:00",
          coGrade: "1",
          no2Value: "0.011",
          stationName: "신촌로",
          pm10Grade: "1",
          o3Value: "0.040",
        },
        {
          so2Grade: "1",
          coFlag: null,
          khaiValue: "58",
          so2Value: "0.002",
          coValue: "0.3",
          pm25Flag: null,
          pm10Flag: null,
          o3Grade: "2",
          pm10Value: "6",
          khaiGrade: "2",
          pm25Value: "2",
          sidoName: "서울",
          no2Flag: null,
          no2Grade: "1",
          o3Flag: null,
          pm25Grade: "1",
          so2Flag: null,
          dataTime: "2021-09-05 12:00",
          coGrade: "1",
          no2Value: "0.008",
          stationName: "강서구",
          pm10Grade: "1",
          o3Value: "0.039",
        },
        {
          so2Grade: "1",
          coFlag: null,
          khaiValue: "58",
          so2Value: "0.002",
          coValue: "0.3",
          pm25Flag: null,
          pm10Flag: null,
          o3Grade: "2",
          pm10Value: "13",
          khaiGrade: "2",
          pm25Value: "8",
          sidoName: "서울",
          no2Flag: null,
          no2Grade: "1",
          o3Flag: null,
          pm25Grade: "1",
          so2Flag: null,
          dataTime: "2021-09-05 12:00",
          coGrade: "1",
          no2Value: "0.015",
          stationName: "공항대로",
          pm10Grade: "1",
          o3Value: "0.039",
        },
        {
          so2Grade: "1",
          coFlag: null,
          khaiValue: "59",
          so2Value: "0.002",
          coValue: "0.4",
          pm25Flag: null,
          pm10Flag: null,
          o3Grade: "2",
          pm10Value: "11",
          khaiGrade: "2",
          pm25Value: "2",
          sidoName: "서울",
          no2Flag: null,
          no2Grade: "1",
          o3Flag: null,
          pm25Grade: "1",
          so2Flag: null,
          dataTime: "2021-09-05 12:00",
          coGrade: "1",
          no2Value: "0.005",
          stationName: "구로구",
          pm10Grade: "1",
          o3Value: "0.041",
        },
        {
          so2Grade: "1",
          coFlag: null,
          khaiValue: "57",
          so2Value: "0.002",
          coValue: "0.3",
          pm25Flag: null,
          pm10Flag: null,
          o3Grade: "2",
          pm10Value: "9",
          khaiGrade: "2",
          pm25Value: "3",
          sidoName: "서울",
          no2Flag: null,
          no2Grade: "1",
          o3Flag: null,
          pm25Grade: "1",
          so2Flag: null,
          dataTime: "2021-09-05 12:00",
          coGrade: "1",
          no2Value: "0.007",
          stationName: "영등포구",
          pm10Grade: "1",
          o3Value: "0.038",
        },
        {
          so2Grade: "1",
          coFlag: null,
          khaiValue: "54",
          so2Value: "0.003",
          coValue: "0.4",
          pm25Flag: null,
          pm10Flag: null,
          o3Grade: "2",
          pm10Value: "19",
          khaiGrade: "2",
          pm25Value: "5",
          sidoName: "서울",
          no2Flag: null,
          no2Grade: "1",
          o3Flag: null,
          pm25Grade: "1",
          so2Flag: null,
          dataTime: "2021-09-05 12:00",
          coGrade: "1",
          no2Value: "0.013",
          stationName: "영등포로",
          pm10Grade: "1",
          o3Value: "0.035",
        },
        {
          so2Grade: "1",
          coFlag: null,
          khaiValue: "60",
          so2Value: "0.002",
          coValue: "0.2",
          pm25Flag: null,
          pm10Flag: null,
          o3Grade: "2",
          pm10Value: "8",
          khaiGrade: "2",
          pm25Value: "1",
          sidoName: "서울",
          no2Flag: null,
          no2Grade: "1",
          o3Flag: null,
          pm25Grade: "1",
          so2Flag: null,
          dataTime: "2021-09-05 12:00",
          coGrade: "1",
          no2Value: "0.006",
          stationName: "동작구",
          pm10Grade: "1",
          o3Value: "0.042",
        },
        {
          so2Grade: "1",
          coFlag: null,
          khaiValue: "53",
          so2Value: "0.002",
          coValue: "0.3",
          pm25Flag: null,
          pm10Flag: null,
          o3Grade: "2",
          pm10Value: "15",
          khaiGrade: "2",
          pm25Value: "7",
          sidoName: "서울",
          no2Flag: null,
          no2Grade: "1",
          o3Flag: null,
          pm25Grade: "1",
          so2Flag: null,
          dataTime: "2021-09-05 12:00",
          coGrade: "1",
          no2Value: "0.015",
          stationName: "동작대로 중앙차로",
          pm10Grade: "1",
          o3Value: "0.033",
        },
        {
          so2Grade: "1",
          coFlag: null,
          khaiValue: "58",
          so2Value: "0.002",
          coValue: "0.3",
          pm25Flag: null,
          pm10Flag: null,
          o3Grade: "2",
          pm10Value: "9",
          khaiGrade: "2",
          pm25Value: "2",
          sidoName: "서울",
          no2Flag: null,
          no2Grade: "1",
          o3Flag: null,
          pm25Grade: "1",
          so2Flag: null,
          dataTime: "2021-09-05 12:00",
          coGrade: "1",
          no2Value: "0.009",
          stationName: "관악구",
          pm10Grade: "1",
          o3Value: "0.040",
        },
        {
          so2Grade: "1",
          coFlag: null,
          khaiValue: "56",
          so2Value: "0.003",
          coValue: "0.2",
          pm25Flag: null,
          pm10Flag: null,
          o3Grade: "2",
          pm10Value: "7",
          khaiGrade: "2",
          pm25Value: "1",
          sidoName: "서울",
          no2Flag: null,
          no2Grade: "1",
          o3Flag: null,
          pm25Grade: "1",
          so2Flag: null,
          dataTime: "2021-09-05 12:00",
          coGrade: "1",
          no2Value: "0.006",
          stationName: "강남구",
          pm10Grade: "1",
          o3Value: "0.037",
        },
        {
          so2Grade: "1",
          coFlag: null,
          khaiValue: "57",
          so2Value: "0.002",
          coValue: "0.3",
          pm25Flag: null,
          pm10Flag: null,
          o3Grade: "2",
          pm10Value: "9",
          khaiGrade: "2",
          pm25Value: "1",
          sidoName: "서울",
          no2Flag: null,
          no2Grade: "1",
          o3Flag: null,
          pm25Grade: "1",
          so2Flag: null,
          dataTime: "2021-09-05 12:00",
          coGrade: "1",
          no2Value: "0.006",
          stationName: "서초구",
          pm10Grade: "1",
          o3Value: "0.038",
        },
        {
          so2Grade: "1",
          coFlag: null,
          khaiValue: "58",
          so2Value: "0.002",
          coValue: "0.4",
          pm25Flag: null,
          pm10Flag: null,
          o3Grade: "2",
          pm10Value: "7",
          khaiGrade: "2",
          pm25Value: "3",
          sidoName: "서울",
          no2Flag: null,
          no2Grade: "1",
          o3Flag: null,
          pm25Grade: "1",
          so2Flag: null,
          dataTime: "2021-09-05 12:00",
          coGrade: "1",
          no2Value: "0.006",
          stationName: "도산대로",
          pm10Grade: "1",
          o3Value: "0.040",
        },
        {
          so2Grade: null,
          coFlag: null,
          khaiValue: "51",
          so2Value: "-",
          coValue: "0.4",
          pm25Flag: "자료이상",
          pm10Flag: null,
          o3Grade: "2",
          pm10Value: "7",
          khaiGrade: "2",
          pm25Value: "-",
          sidoName: "서울",
          no2Flag: null,
          no2Grade: "1",
          o3Flag: null,
          pm25Grade: null,
          so2Flag: "자료이상",
          dataTime: "2021-09-05 12:00",
          coGrade: "1",
          no2Value: "0.016",
          stationName: "강남대로",
          pm10Grade: "1",
          o3Value: "0.031",
        },
        {
          so2Grade: "1",
          coFlag: null,
          khaiValue: "58",
          so2Value: "0.002",
          coValue: "0.3",
          pm25Flag: null,
          pm10Flag: null,
          o3Grade: "2",
          pm10Value: "11",
          khaiGrade: "2",
          pm25Value: "7",
          sidoName: "서울",
          no2Flag: null,
          no2Grade: "1",
          o3Flag: null,
          pm25Grade: "1",
          so2Flag: null,
          dataTime: "2021-09-05 12:00",
          coGrade: "1",
          no2Value: "0.008",
          stationName: "송파구",
          pm10Grade: "1",
          o3Value: "0.039",
        },
        {
          so2Grade: "1",
          coFlag: null,
          khaiValue: "53",
          so2Value: "0.002",
          coValue: "0.2",
          pm25Flag: null,
          pm10Flag: null,
          o3Grade: "2",
          pm10Value: "5",
          khaiGrade: "2",
          pm25Value: "1",
          sidoName: "서울",
          no2Flag: null,
          no2Grade: "1",
          o3Flag: null,
          pm25Grade: "1",
          so2Flag: null,
          dataTime: "2021-09-05 12:00",
          coGrade: "1",
          no2Value: "0.005",
          stationName: "강동구",
          pm10Grade: "1",
          o3Value: "0.034",
        },
        {
          so2Grade: "1",
          coFlag: null,
          khaiValue: "52",
          so2Value: "0.002",
          coValue: "0.3",
          pm25Flag: null,
          pm10Flag: null,
          o3Grade: "2",
          pm10Value: "16",
          khaiGrade: "2",
          pm25Value: "3",
          sidoName: "서울",
          no2Flag: null,
          no2Grade: "1",
          o3Flag: null,
          pm25Grade: "1",
          so2Flag: null,
          dataTime: "2021-09-05 12:00",
          coGrade: "1",
          no2Value: "0.017",
          stationName: "천호대로",
          pm10Grade: "1",
          o3Value: "0.032",
        },
        {
          so2Grade: "1",
          coFlag: null,
          khaiValue: "58",
          so2Value: "0.003",
          coValue: "0.3",
          pm25Flag: null,
          pm10Flag: null,
          o3Grade: "2",
          pm10Value: "17",
          khaiGrade: "2",
          pm25Value: "14",
          sidoName: "서울",
          no2Flag: null,
          no2Grade: "1",
          o3Flag: null,
          pm25Grade: "1",
          so2Flag: null,
          dataTime: "2021-09-05 12:00",
          coGrade: "1",
          no2Value: "0.007",
          stationName: "금천구",
          pm10Grade: "1",
          o3Value: "0.040",
        },
        {
          so2Grade: "1",
          coFlag: null,
          khaiValue: "61",
          so2Value: "0.003",
          coValue: "0.4",
          pm25Flag: null,
          pm10Flag: null,
          o3Grade: "1",
          pm10Value: "15",
          khaiGrade: "2",
          pm25Value: "4",
          sidoName: "서울",
          no2Flag: null,
          no2Grade: "2",
          o3Flag: null,
          pm25Grade: "1",
          so2Flag: null,
          dataTime: "2021-09-05 12:00",
          coGrade: "1",
          no2Value: "0.037",
          stationName: "시흥대로",
          pm10Grade: "1",
          o3Value: "0.021",
        },
        {
          so2Grade: "1",
          coFlag: null,
          khaiValue: "61",
          so2Value: "0.002",
          coValue: "0.2",
          pm25Flag: null,
          pm10Flag: null,
          o3Grade: "2",
          pm10Value: "8",
          khaiGrade: "2",
          pm25Value: "1",
          sidoName: "서울",
          no2Flag: null,
          no2Grade: "1",
          o3Flag: null,
          pm25Grade: "1",
          so2Flag: null,
          dataTime: "2021-09-05 12:00",
          coGrade: "1",
          no2Value: "0.005",
          stationName: "강북구",
          pm10Grade: "1",
          o3Value: "0.043",
        },
        {
          so2Grade: "1",
          coFlag: null,
          khaiValue: "58",
          so2Value: "0.003",
          coValue: "0.3",
          pm25Flag: null,
          pm10Flag: null,
          o3Grade: "2",
          pm10Value: "8",
          khaiGrade: "2",
          pm25Value: "4",
          sidoName: "서울",
          no2Flag: null,
          no2Grade: "1",
          o3Flag: null,
          pm25Grade: "1",
          so2Flag: null,
          dataTime: "2021-09-05 12:00",
          coGrade: "1",
          no2Value: "0.008",
          stationName: "양천구",
          pm10Grade: "1",
          o3Value: "0.039",
        },
        {
          so2Grade: "1",
          coFlag: null,
          khaiValue: "61",
          so2Value: "0.002",
          coValue: "0.3",
          pm25Flag: null,
          pm10Flag: null,
          o3Grade: "2",
          pm10Value: "5",
          khaiGrade: "2",
          pm25Value: "1",
          sidoName: "서울",
          no2Flag: null,
          no2Grade: "1",
          o3Flag: null,
          pm25Grade: "1",
          so2Flag: null,
          dataTime: "2021-09-05 12:00",
          coGrade: "1",
          no2Value: "0.004",
          stationName: "노원구",
          pm10Grade: "1",
          o3Value: "0.043",
        },
        {
          so2Grade: "1",
          coFlag: null,
          khaiValue: "48",
          so2Value: "0.003",
          coValue: "0.4",
          pm25Flag: null,
          pm10Flag: null,
          o3Grade: "1",
          pm10Value: "22",
          khaiGrade: "1",
          pm25Value: "4",
          sidoName: "서울",
          no2Flag: null,
          no2Grade: "1",
          o3Flag: null,
          pm25Grade: "1",
          so2Flag: null,
          dataTime: "2021-09-05 12:00",
          coGrade: "1",
          no2Value: "0.019",
          stationName: "화랑로",
          pm10Grade: "1",
          o3Value: "0.029",
        },
        {
          so2Grade: "1",
          coFlag: null,
          khaiValue: "56",
          so2Value: "0.003",
          coValue: "0.3",
          pm25Flag: null,
          pm10Flag: null,
          o3Grade: "2",
          pm10Value: "6",
          khaiGrade: "2",
          pm25Value: "1",
          sidoName: "서울",
          no2Flag: null,
          no2Grade: "1",
          o3Flag: null,
          pm25Grade: "1",
          so2Flag: null,
          dataTime: "2021-09-05 12:00",
          coGrade: "1",
          no2Value: "0.009",
          stationName: "중구",
          pm10Grade: "1",
          o3Value: "0.037",
        },
        {
          so2Grade: "1",
          coFlag: null,
          khaiValue: "42",
          so2Value: "0.003",
          coValue: "0.4",
          pm25Flag: null,
          pm10Flag: null,
          o3Grade: "1",
          pm10Value: "28",
          khaiGrade: "1",
          pm25Value: "8",
          sidoName: "서울",
          no2Flag: null,
          no2Grade: "1",
          o3Flag: null,
          pm25Grade: "1",
          so2Flag: null,
          dataTime: "2021-09-05 12:00",
          coGrade: "1",
          no2Value: "0.013",
          stationName: "한강대로",
          pm10Grade: "1",
          o3Value: "0.022",
        },
        {
          so2Grade: "1",
          coFlag: null,
          khaiValue: "59",
          so2Value: "0.003",
          coValue: "0.3",
          pm25Flag: null,
          pm10Flag: null,
          o3Grade: "2",
          pm10Value: "3",
          khaiGrade: "2",
          pm25Value: "1",
          sidoName: "서울",
          no2Flag: null,
          no2Grade: "1",
          o3Flag: null,
          pm25Grade: "1",
          so2Flag: null,
          dataTime: "2021-09-05 12:00",
          coGrade: "1",
          no2Value: "0.006",
          stationName: "종로구",
          pm10Grade: "1",
          o3Value: "0.041",
        },
        {
          so2Grade: "1",
          coFlag: null,
          khaiValue: "-",
          so2Value: "0.003",
          coValue: "0.3",
          pm25Flag: null,
          pm10Flag: null,
          o3Grade: "2",
          pm10Value: "9",
          khaiGrade: null,
          pm25Value: "3",
          sidoName: "서울",
          no2Flag: null,
          no2Grade: "1",
          o3Flag: null,
          pm25Grade: null,
          so2Flag: null,
          dataTime: "2021-09-05 12:00",
          coGrade: "1",
          no2Value: "0.009",
          stationName: "청계천로",
          pm10Grade: "1",
          o3Value: "0.041",
        },
        {
          so2Grade: "1",
          coFlag: null,
          khaiValue: "52",
          so2Value: "0.003",
          coValue: "0.1",
          pm25Flag: null,
          pm10Flag: null,
          o3Grade: "2",
          pm10Value: "19",
          khaiGrade: "2",
          pm25Value: "3",
          sidoName: "서울",
          no2Flag: null,
          no2Grade: "1",
          o3Flag: null,
          pm25Grade: "1",
          so2Flag: null,
          dataTime: "2021-09-05 12:00",
          coGrade: "1",
          no2Value: "0.015",
          stationName: "종로",
          pm10Grade: "1",
          o3Value: "0.032",
        },
        {
          so2Grade: "1",
          coFlag: null,
          khaiValue: "53",
          so2Value: "0.003",
          coValue: "0.2",
          pm25Flag: null,
          pm10Flag: null,
          o3Grade: "2",
          pm10Value: "11",
          khaiGrade: "2",
          pm25Value: "3",
          sidoName: "서울",
          no2Flag: null,
          no2Grade: "1",
          o3Flag: null,
          pm25Grade: "1",
          so2Flag: null,
          dataTime: "2021-09-05 12:00",
          coGrade: "1",
          no2Value: "0.007",
          stationName: "용산구",
          pm10Grade: "1",
          o3Value: "0.033",
        },
        {
          so2Grade: "1",
          coFlag: null,
          khaiValue: "54",
          so2Value: "0.004",
          coValue: "0.3",
          pm25Flag: null,
          pm10Flag: null,
          o3Grade: "2",
          pm10Value: "5",
          khaiGrade: "2",
          pm25Value: "1",
          sidoName: "서울",
          no2Flag: null,
          no2Grade: "1",
          o3Flag: null,
          pm25Grade: "1",
          so2Flag: null,
          dataTime: "2021-09-05 12:00",
          coGrade: "1",
          no2Value: "0.006",
          stationName: "광진구",
          pm10Grade: "1",
          o3Value: "0.035",
        },
        {
          so2Grade: "1",
          coFlag: null,
          khaiValue: "61",
          so2Value: "0.002",
          coValue: "0.2",
          pm25Flag: null,
          pm10Flag: null,
          o3Grade: "2",
          pm10Value: "6",
          khaiGrade: "2",
          pm25Value: "1",
          sidoName: "서울",
          no2Flag: null,
          no2Grade: "1",
          o3Flag: null,
          pm25Grade: "1",
          so2Flag: null,
          dataTime: "2021-09-05 12:00",
          coGrade: "1",
          no2Value: "0.007",
          stationName: "성동구",
          pm10Grade: "1",
          o3Value: "0.043",
        },
        {
          so2Grade: null,
          coFlag: null,
          khaiValue: "-",
          so2Value: "-",
          coValue: "0.2",
          pm25Flag: "자료이상",
          pm10Flag: "자료이상",
          o3Grade: "2",
          pm10Value: "-",
          khaiGrade: null,
          pm25Value: "-",
          sidoName: "서울",
          no2Flag: null,
          no2Grade: "1",
          o3Flag: null,
          pm25Grade: null,
          so2Flag: "자료이상",
          dataTime: "2021-09-05 12:00",
          coGrade: "1",
          no2Value: "0.002",
          stationName: "강변북로",
          pm10Grade: null,
          o3Value: "0.039",
        },
        {
          so2Grade: "1",
          coFlag: null,
          khaiValue: "60",
          so2Value: "0.003",
          coValue: "0.2",
          pm25Flag: null,
          pm10Flag: null,
          o3Grade: "2",
          pm10Value: "6",
          khaiGrade: "2",
          pm25Value: "1",
          sidoName: "서울",
          no2Flag: null,
          no2Grade: "1",
          o3Flag: null,
          pm25Grade: "1",
          so2Flag: null,
          dataTime: "2021-09-05 12:00",
          coGrade: "1",
          no2Value: "0.004",
          stationName: "중랑구",
          pm10Grade: "1",
          o3Value: "0.042",
        },
        {
          so2Grade: "1",
          coFlag: null,
          khaiValue: "60",
          so2Value: "0.003",
          coValue: "0.2",
          pm25Flag: null,
          pm10Flag: null,
          o3Grade: "2",
          pm10Value: "5",
          khaiGrade: "2",
          pm25Value: "1",
          sidoName: "서울",
          no2Flag: null,
          no2Grade: "1",
          o3Flag: null,
          pm25Grade: "1",
          so2Flag: null,
          dataTime: "2021-09-05 12:00",
          coGrade: "1",
          no2Value: "0.006",
          stationName: "동대문구",
          pm10Grade: "1",
          o3Value: "0.042",
        },
        {
          so2Grade: "1",
          coFlag: null,
          khaiValue: "53",
          so2Value: "0.003",
          coValue: "0.3",
          pm25Flag: null,
          pm10Flag: null,
          o3Grade: "2",
          pm10Value: "12",
          khaiGrade: "2",
          pm25Value: "4",
          sidoName: "서울",
          no2Flag: null,
          no2Grade: "1",
          o3Flag: null,
          pm25Grade: "1",
          so2Flag: null,
          dataTime: "2021-09-05 12:00",
          coGrade: "1",
          no2Value: "0.009",
          stationName: "홍릉로",
          pm10Grade: "1",
          o3Value: "0.033",
        },
        {
          so2Grade: null,
          coFlag: null,
          khaiValue: "57",
          so2Value: "-",
          coValue: "0.4",
          pm25Flag: null,
          pm10Flag: null,
          o3Grade: "2",
          pm10Value: "13",
          khaiGrade: "2",
          pm25Value: "1",
          sidoName: "서울",
          no2Flag: null,
          no2Grade: "1",
          o3Flag: null,
          pm25Grade: "1",
          so2Flag: "자료이상",
          dataTime: "2021-09-05 12:00",
          coGrade: "1",
          no2Value: "0.009",
          stationName: "성북구",
          pm10Grade: "1",
          o3Value: "0.038",
        },
        {
          so2Grade: "1",
          coFlag: null,
          khaiValue: "54",
          so2Value: "0.002",
          coValue: "0.2",
          pm25Flag: null,
          pm10Flag: null,
          o3Grade: "2",
          pm10Value: "8",
          khaiGrade: "2",
          pm25Value: "3",
          sidoName: "서울",
          no2Flag: null,
          no2Grade: "1",
          o3Flag: null,
          pm25Grade: "1",
          so2Flag: null,
          dataTime: "2021-09-05 12:00",
          coGrade: "1",
          no2Value: "0.012",
          stationName: "정릉로",
          pm10Grade: "1",
          o3Value: "0.035",
        },
      ],
      pageNo: 1,
      numOfRows: 100,
    },
    header: { resultMsg: "NORMAL_CODE", resultCode: "00" },
  },
};

const {
  response: {
    body: { items },
  },
} = DATA;

const $target = document.querySelector("#app");

new SidoNameList({
  $target,
  initialState: items,
});
